name: contacts_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  # State management 
  flutter_bloc: ^8.1.3

  # Network Layer
  vexana: ^3.5.4

  # Json Serializable
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Email Validator
  email_validator: ^2.1.17

  # SQLite Plugin
  sqflite: ^2.3.0

  # Persistent storage
  shared_preferences: ^2.2.2

  # Image Picker
  image_picker: ^1.0.4

  # Toast Plugin
  fluttertoast: ^8.2.2

  # Network Check
  connectivity_plus: ^4.0.1






dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

  # Build Runner
  build_runner: ^2.4.6
  # Launcher Icons
  flutter_launcher_icons: "^0.13.1"

  # App Icon Setup
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
   


